# Generated by Django 3.2.5 on 2021-12-05 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=1000)),
                ('passport', models.ImageField(blank=True, upload_to='students/notices_file/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
