# Generated by Django 3.2.5 on 2021-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_notice_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_info',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
    ]
