# Generated by Django 3.2.5 on 2021-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211205_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy_info',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
