# Generated by Django 3.2.5 on 2021-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_vacancy_info_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_info',
            name='passport',
            field=models.ImageField(blank=True, upload_to='media/notices_file/'),
        ),
        migrations.AlterField(
            model_name='vacancy_info',
            name='image_vacancy',
            field=models.ImageField(blank=True, upload_to='media/vacancy_file/'),
        ),
    ]
