# Generated by Django 3.2.5 on 2021-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20211205_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_info',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/notices_file/'),
        ),
        migrations.AlterField(
            model_name='vacancy_info',
            name='image_vacancy',
            field=models.ImageField(blank=True, upload_to='students/vacancy_file/'),
        ),
    ]
