# Generated by Django 3.2.5 on 2021-12-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211205_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbulkupload',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='students/bulkupload/'),
        ),
    ]
