# Generated by Django 3.2.5 on 2021-12-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_notices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='current',
        ),
    ]
