# Generated by Django 3.2.5 on 2021-12-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_alter_notices_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notices',
        ),
    ]
