# Generated by Django 3.2.5 on 2021-11-30 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('class_numbers', models.IntegerField()),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?977?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=250)),
                ('grade_value', models.FloatField(max_length=3)),
                ('review', models.TextField(max_length=500)),
            ],
        ),
    ]
