# Generated by Django 3.2.5 on 2021-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_student',
            name='class_numbers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission_student',
            name='grade_value',
            field=models.FloatField(blank=True, max_length=3),
        ),
    ]
